### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by cappelikan** [AndreyBarmaley/qxkb5#2]
/usr/include/xcb/xkb.h:727:19: error: declaration does not declare anything [-fpermissive]
  727 |     uint8_t       explicit;
      |                   ^~~~~~~~
/usr/include/xcb/xkb.h:2005:30: error: expected unqualified-id before ‘explicit’
 2005 |     xcb_xkb_set_explicit_t  *explicit;
      |                              ^~~~~~~~
make[2]: *** [CMakeFiles/qxkb5.dir/build.make:298: CMakeFiles/qxkb5.dir/qxkb5_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/qxkb5.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by fk0** [comment]
I'm facing same error. Does it compile with another version of xkb?
I am using Arch btw.

**Comment by AndreyBarmaley** [comment]
fixed
