### ISSUE TITLE
PKGBUILD

### ISSUE THREAD

**Issue by Ved-un** [AndreyBarmaley/qxkb5#3]
Извиняюсь. 
Можете ли вы написать PKGBUILD для AUR 
или хотя бы опубликовать инструкцию по сборке и установке вашего пакета?

Хотелось бы установить и попробовать вашу программу.

**Comment by AndreyBarmaley** [comment]
qmake-qt5
make
cp qxkb5 /usr/local/bin


20.03.2022, ***@***.***> написал(а):

**Comment by Ved-un** [comment]
Спасибо. Извините за беспокойство.
